2020-05-31 20:38:10,081 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 20:53:59,225 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 20:54:47,022 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 20:57:50,091 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 21:03:50,576 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 21:04:07,133 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 21:04:17,769 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 21:05:29,082 ERROR: Exception on /expore [GET] [in /Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/routes.py", line 140, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/templates/index.html", line 3, in top-level template code
    {% extends "base.html" %}
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/templates/index.html", line 20, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-05-31 21:10:28,305 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 21:10:32,500 ERROR: Exception on /expore [GET] [in /Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/routes.py", line 139, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/templates/index.html", line 3, in top-level template code
    {% extends "base.html" %}
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/templates/index.html", line 20, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-05-31 21:17:36,261 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 21:17:44,922 ERROR: Exception on /expore [GET] [in /Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/routes.py", line 138, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/markwharry/.pyenv/versions/3.8.1/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/templates/index.html", line 3, in top-level template code
    {% extends "base.html" %}
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/templates/index.html", line 20, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-05-31 21:20:56,157 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 21:26:48,045 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
2020-05-31 21:28:14,972 INFO: Microblog startup [in /Users/markwharry/Dropbox/Mark/Files/Programming/PyCharm/microblog/app/__init__.py:44]
